#include "signalDefinitions.h"

#define ONCHANGE_TURNOUT_101() \
  SET_LMAINM1_LMAINLEAD() \
  SET_M1LMAIN() \
  SET_LEADLMAIN() \
  SET_M1M1() \
  SET_M2M1LEAD() \
  SET_RMAINM1_RMAINM2()

#define ONCHANGE_TURNOUT_102() \
  SET_RMAINM1_RMAINM2() \
  SET_M1RMAIN() \
  SET_M2RMAIN() \
  SET_M1M1M2() \
  SET_LEADM2() \
  SET_LMAINM1_LMAINLEAD()

#define ONCHANGE_CROSSOVER() \
  SET_M1M1() \
  SET_M2M1LEAD() \
  SET_M1M1M2() \
  SET_LEADM2() \
  SET_LMAINM1_LMAINLEAD() \
  SET_RMAINM1_RMAINM2()

#define ONCHANGE_TURNOUT_YARD_EXIT() \
  SET_YARD() \
  SET_M1M1M2() \
  SET_LEADM2() \
  SET_M2M1LEAD()
