#include "signalStates.h"

// CP 101
#define L_MAIN_M1 111
#define L_MAIN_LEAD 115
#define M1_L_MAIN 105
#define LEAD_L_MAIN 107

// CP 102
#define R_MAIN_M1 154
#define R_MAIN_M2 158
#define M1_R_MAIN 161
#define M2_R_MAIN 163

#define ONCHANGE_TURNOUT_101() \
  IFCLOSED(101) \
    CLEAR_TWO_HEADS(L_MAIN_M1, L_MAIN_LEAD) \
    CLEAR_ONE_HEAD(M1_L_MAIN) \
    STOP_ONE_HEAD(LEAD_L_MAIN) \
  ELSE \
    APPROACH_TWO_HEADS(L_MAIN_M1, L_MAIN_LEAD) \
    STOP_ONE_HEAD(M1_L_MAIN) \
    APPROACH_ONE_HEAD(LEAD_L_MAIN) \
  ENDIF

#define ONCHANGE_TURNOUT_102() \
  IFCLOSED(102) \
    CLEAR_TWO_HEADS(R_MAIN_M1, R_MAIN_M2) \
    CLEAR_ONE_HEAD(M1_R_MAIN) \
    STOP_ONE_HEAD(M2_R_MAIN) \
  ELSE \
    APPROACH_TWO_HEADS(R_MAIN_M1, R_MAIN_M2) \
    STOP_ONE_HEAD(M1_R_MAIN) \
    APPROACH_ONE_HEAD(M2_R_MAIN) \
  ENDIF
